"""Add remaining iTunes fields (keywords, category, ep type, item image)

Revision ID: 093a8f50fa03
Revises: ded4b70feadb
Create Date: 2025-04-27 05:01:05.868338

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "093a8f50fa03"
down_revision = "ded4b70feadb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("itunes_author", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_subtitle", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_summary", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_explicit", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("itunes_type", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("itunes_owner_name", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_owner_email", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_keywords", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("itunes_categories_json", sa.Text(), nullable=True)
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("itunes_subtitle", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_summary", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("itunes_explicit", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("itunes_episode_type", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("itunes_image_url", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("itunes_image_url")
        batch_op.drop_column("itunes_episode_type")
        batch_op.drop_column("itunes_explicit")
        batch_op.drop_column("itunes_summary")
        batch_op.drop_column("itunes_subtitle")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("itunes_categories_json")
        batch_op.drop_column("itunes_keywords")
        batch_op.drop_column("itunes_owner_email")
        batch_op.drop_column("itunes_owner_name")
        batch_op.drop_column("itunes_type")
        batch_op.drop_column("itunes_explicit")
        batch_op.drop_column("itunes_summary")
        batch_op.drop_column("itunes_subtitle")
        batch_op.drop_column("itunes_author")
        batch_op.drop_column("language")

    # ### end Alembic commands ###
