"""Change Post.release_date to DateTime type

Revision ID: 57b6a266b535
Revises: 093a8f50fa03
Create Date: 2025-04-27 05:11:37.814222

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57b6a266b535"
down_revision = "093a8f50fa03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "release_date",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "release_date",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
